cluster: vanilla

primitives:
- cobble: 0 # omnipresent, easily generated.
- wood: 1
# NOTE: wood should be moved to equivalents.
- oak wood: 1
- spruce wood: 1
- dirt: 1
- sand: 1
- sandstone: 2
- gravel: 1
- iron ore: 16
- coal: 8
- coal ore: 8
- gold ore: 90 # 3 times less numerous than redstone
- diamond ore: 250 # 25x less than iron
- diamond: 250
- emerald ore: 2500 # 10x less than diamond
- emerald: 2500
- redstone ore: 48 # 3x less than iron
- redstone: 12 # 4-5 per ore
- lapis lazuli ore: 200 # 23x less than iron
- lapis: 32 # 4-8 per ore
- flint: 3
- wool: 5
- water:
    cost: 1
    stacks: false
- lava: 11 # 1.4x more than iron
- leather: 10
- clay: 15
- string: 3
- obsidian: 30
- snowball: 1
- ice: 2


crafts:
- stone:
    machine: furnace
    ingredients: [cobble]
- furnace: [cobble*8]
- planks:
    makes: 4
    ingredients: [wood]
- stick:
    makes: 4
    ingredients: [planks*2]
- charcoal:
    machine: furnace
    ingredients: [wood]
- brick:
    machine: furnace
    ingredients: [clay]
- glass:
    machine: furnace
    ingredients: [sand]
- glass pane:
    ingredients: [glass*6]
    makes: 16
- torch:
    makes: 4
    ingredients: [stick, charcoal]
- torch:
    makes: 4
    ingredients: [stick, coal]
- redstone torch: [stick, redstone]
- iron:
    machine: furnace
    ingredients: [iron ore]
    compatible: all
- gold ingot:
    machine: furnace
    ingredients: [gold ore]
    compatible: all
- iron bars:
    makes: 16
    ingredients: [iron*6]
    shape: i i i i i i ~ ~ ~
- piston: 
    ingredients: [planks*3, cobble*4, iron, redstone]
    shape: p p p c i c c r c
- sticky piston: [piston, slimeball]
- lever: [cobble, stick]
- bucket: [iron*3]
- water bucket: [water, bucket]
- lava bucket: [lava, bucket]
- chest: [planks*8]
- pressure plate: [planks*2]
- bottle: [glass*3]
- bowl: 
    ingredients: [wood*3]
    makes: 4
- gold nugget:
    makes: 9
    ingredients: [gold ingot]
    compatible: all
- paper:
    makes: 3
    ingredients: [sugar cane*3]
- bookcase: [book*3, planks*6]
- book: [leather, paper*3]
- minecart: 
    ingredients: [iron*5]
    shape: i ~ i i i i ~ ~ ~
- chestcart: [minecart, chest]
- dispenser: 
    ingredients: [cobble*6, bow, redstone]
- fence gate: 
    ingredients: [stick*4, planks*2]
    shape: ~ ~ ~ s p s s p s
- door: 
    ingredients: [planks*6]
    shape: p p ~ p p ~ p p ~
- iron door: 
    ingredients: [iron*6]
    shape: i i ~ i i ~ i i ~
- TNT:
    ingredients: [gunpowder*5, sand*4]
    shape: g s g s g s g s g
- button: [stone*2]
- redstone repeater: #shape naming problem
    ingredients: [redstone torch*2, stone*3, redstone]
- redstone lamp:
    ingredients: [redstone*4, glowstone]
    shape: ~ r ~ r g r ~ r ~
- note block:
    ingredients: [planks*8, redstone]
    shape: p p p p r p p p p
- track:
    ingredients: [iron*6, stick]
    shape: i ~ i i s i i ~ i
    makes: 16
- powered track:
    ingredients: [gold ingot*6, redstone, stick]
    shape: g ~ g g s g g r g
    makes: 6
- detector track:
    ingredients: [iron*6, pressure plate, redstone]
    makes: 6
- sign:
    ingredients: [planks*6, stick]
    shape: p p p p p ~ s ~
    makes: 3
- jukebox:
    ingredients: [planks*8, diamond]
    shape: p p p p d p p p p
