cluster: ic2

primitives:
- copper ore: 4
- tin ore: 4
- rubber tree sapling: 12
- sticky resin: 3
- UU-matter: 500
- uranium ore: 25

crafts: 
- bronze dust: 
    ingredients: [copper dust*3, tin dust]
    makes: 2
- clay dust:
    ingredients: [clay block]
    makes: 2
- cell:
    makes: 16
    ingredients: [tin ingot*4]
    shape: |
      ~ t ~
      t ~ t
      ~ t ~
- raw carbon fibers: 
    ingredients: [coal dust*4]
    shape: c c c c
- raw carbon mesh: [raw carbon fibers*2]
- mixed metal ingot:
    makes: 2
    ingredients:
      - refined iron*3
      - bronze*3
      - tin ingot*3
- iridium plate:
    ingredients:
    - iridium*4
    - advanced alloy*4
    - diamond
    tag: plain
- reinforced stone:
    makes: 8
    ingredients: [stone*8, advanced alloy]
- reinforced glass:
    makes: 7
    ingredients:
      - glass*7
      - advanced alloy*2
    shape: g a g g g g g a g
- reinforced door:
    ingredients: [reinforced stone*6]
- iron fence: [refined iron*6]
- coal ball:
    ingredients: [coal dust*8, flint]
    shape: c c c c f c c c c
- coal chunk:
    vars: [center]
    ingredients: [compressed coal ball*8, C|$(center)]
    shape: c c c c C c c c c
    center: [iron block, bricks, obsidian]
- luminator:
    ingredients: [refined iron*2, copper cable, glass*5, tin wire]
