cluster: redpower2

primitives:
- silver ore: 8
- copper ore: 4
- tin ore: 4
- nikolite: 50
- sapphire: 40
- ruby: 40
- green sapphire: 40
- basalt cobblestone: 1
- marble: 1
- indigo flower: 1
- rubber wood: 16
- flax seeds: 2

crafts:
- marble brick:
    makes: 4
    ingredients: [marble*4]
- basalt brick:
    makes: 4
    ingredients: [basalt*4]
- sticks:
    makes: 8
    ingredients: [rubber wood]
- indigo dye:
    makes: 2
    ingredients: [indigo flower]
