cluster: redpower2

primitives:
- silver ore: 30
- tungsten ore: 90
- nikolite ore: 50
- nikolite: 50
- sapphire: 40
- ruby: 40
# NOTE: associated gem ores are listed in GT, as it also defines those
- green sapphire: 40
- basalt cobblestone: 16 # 16x less common than marble
- marble: 1
- indigo flower: 1
- rubber wood: 16
- flax seeds: 2

crafts:
- marble brick:
    makes: 4
    ingredients: [marble*4]
- basalt brick:
    makes: 4
    ingredients: [basalt*4]
- sticks:
    makes: 8
    ingredients: [rubber wood]
- indigo dye:
    makes: 2
    ingredients: [indigo flower]
