cluster: railcraft

crafts:
- item loader:
    ingredients: [dispenser, detector - item]
- item unloader:
    ingredients: [dispenser, detector - item]
- advanced item loader:
    ingredients: [redstone*3, steel ingot*4, ender pearl, item loader]
- advanced item unloader:
    ingredients: [redstone*3, steel ingot*4, ender pearl, item unloader]
- cart dispenser: [dispenser, minecart]
- train dispenser: [cart dispenser, crowbar*4, redstone*4] 
- tunnel bore: [minecart*2, furnace*2, steel block*2, chest cart]
- iron bore head: [steel ingot*8, iron block]
- steel bore head: [steel ingot*8, steel block]
- diamond bore head: [steel ingot*8, diamond block]
- feed station: [golden carrot*4, planks*4, steel plate]
- switch lever: [white dye, black dye, red dye, piston, lever, iron]
- switch motor: [white dye, black dye, red dye, piston, receiver circuit, iron]
- detector - $(type): 
    ingredients: [stone pressure plate, $(type)*8]
    type:
      - item/planks
      - powered/cobble
      - any/stone
      - player/stone slab
      - empty/stone brick
      - mob/mossy stone brick
      - mob/mossy cobble
      - animal/oak wood
      - sheep/wool
      - growth/spruce wood
      - explosive/wooden slab
      - advanced/steel ingot
      - train/nether brick
      - tank/brick
      - villager/leather
      - locomotive/infernal brick
      - age/spruce wood


